FROM ubuntu:latest

#install software
RUN apt-get update --fix-missing
RUN apt-get install -y ca-certificates
RUN apt-get install curl --yes

RUN mkdir -p /app/

COPY bin/goway-sidecar /app

EXPOSE 5000

WORKDIR /app


